services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # - ASR_MODEL=tiny
      # - ASR_MODEL=base
      # - ASR_MODEL=small
      # - ASR_MODEL=medium
      - ASR_MODEL=large
    ports:
      - '8000:8000'    
    volumes:
      - .:/code
      - ./cache:/root/.cache/whisper:rw
